webserver:
  port: 8080
  path: /cargarFactura
  method: POST
webservice_dian:
  url: "https://facturaelectronica.dian.gov.co/habilitacion/B2BIntegrationEngine/FacturaElectronica"
mongo_config:
  url: "mongodb://root:yTRyg0Zm11@172.17.0.7:27017/?authSource=admin"
  database: facele
  timeout: 10
rabbit_config:
  url: amqp://user:UK7yAQYzcL@10.104.17.26:5672/
  envio_dian_queue:
    name: enviarFacturaQ 
  notificacion_queue:
    name: notificarFacturaQ
