webServer:
   port: 8080
   path: /cargarFactura
   method: POST
webServiceDian:
   url: https://facturaelectronica.dian.gov.co/habilitacion/B2BIntegrationEngine/FacturaElectronica
mongoConfig:
   host: 172.17.0.2
   port: 27017
   database: facele
envioDianQueue:
   name: enviarFacturaQ 
notificacionQueue:
   name: notificarFacturaQ
