webServer:
   port: 8080
   path: /cargarFactura
   method: POST
webServiceDian:
   url: https://facturaelectronica.dian.gov.co/habilitacion/B2BIntegrationEngine/FacturaElectronica
mongoConfig:
   url: "mongodb://172.17.0.3:27017"
   database: facele
   timeout: 10
envioDianQueue:
   name: enviarFacturaQ 
notificacionQueue:
   name: notificarFacturaQ
